{
 "title": "Four Golden Signals",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(requests[1m]))" }
   ]
  },
  {
   "title": "Duration Latency Buckets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "latency_bucket" }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(requests {code!=\"200\"})) /((sum(requests {code=\"200\"})) + sum(requests {code!=\"200\"}))"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "saturation" }
   ]
  }
 ]
}